services:
  - type: web
    name: grand-aurelia-hospitality
    env: node
    plan: free
    buildCommand: "npm run install:all && npm run build"
    startCommand: "npm run server"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
